# Generated by Django 5.2 on 2025-05-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='status',
            field=models.CharField(choices=[('진행중', '진행중'), ('성공', '성공'), ('실패', '실패')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='status',
            field=models.CharField(choices=[('진행중', '진행중'), ('성공', '성공'), ('실패', '실패')], default='PR', max_length=10),
        ),
    ]
