# Generated by Django 5.2 on 2025-05-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_alter_challenge_status_alter_userchallenge_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallenge',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='participation_images/'),
        ),
    ]
