// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTzwAQSKA0CO89aL1w6QN8vzvr3z83lXQ',
    appId: '1:943584383835:web:779d206ddaa85c4e4ac07e',
    messagingSenderId: '943584383835',
    projectId: 'greeners-a5835',
    authDomain: 'greeners-a5835.firebaseapp.com',
    storageBucket: 'greeners-a5835.firebasestorage.app',
    measurementId: 'G-XBLX67HH1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtZFvJAQrLYpyBJd9lqkcsxPegS_loj7w',
    appId: '1:943584383835:android:f78a89df13e368794ac07e',
    messagingSenderId: '943584383835',
    projectId: 'greeners-a5835',
    storageBucket: 'greeners-a5835.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVolg-4vAnl8lgOo2-QA5sT2v8WGWBPxo',
    appId: '1:943584383835:ios:53b874306482ae424ac07e',
    messagingSenderId: '943584383835',
    projectId: 'greeners-a5835',
    storageBucket: 'greeners-a5835.firebasestorage.app',
    androidClientId: '943584383835-f1ce08bvq3c5uoja81e7r8g5ilinc77a.apps.googleusercontent.com',
    iosClientId: '943584383835-glhgv6db9pkm5hvm8aj7qakddumamuq1.apps.googleusercontent.com',
    iosBundleId: 'com.example.greenersSc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVolg-4vAnl8lgOo2-QA5sT2v8WGWBPxo',
    appId: '1:943584383835:ios:53b874306482ae424ac07e',
    messagingSenderId: '943584383835',
    projectId: 'greeners-a5835',
    storageBucket: 'greeners-a5835.firebasestorage.app',
    androidClientId: '943584383835-f1ce08bvq3c5uoja81e7r8g5ilinc77a.apps.googleusercontent.com',
    iosClientId: '943584383835-glhgv6db9pkm5hvm8aj7qakddumamuq1.apps.googleusercontent.com',
    iosBundleId: 'com.example.greenersSc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTzwAQSKA0CO89aL1w6QN8vzvr3z83lXQ',
    appId: '1:943584383835:web:a6fa0635460562544ac07e',
    messagingSenderId: '943584383835',
    projectId: 'greeners-a5835',
    authDomain: 'greeners-a5835.firebaseapp.com',
    storageBucket: 'greeners-a5835.firebasestorage.app',
    measurementId: 'G-T3WJJ1CLHC',
  );

}